#!/bin/bash
function workspaces() {
  wf="$(swaymsg -p -t get_workspaces | grep '(focused)' | awk '{print $2}')"
  wu="$(swaymsg -p -t get_workspaces  | grep 'Workspace' | grep -v $wf | awk '{print $2}')"

  echo $wf
  echo $wu
}
