
foreground              #e6dce5
background              #2a2462

color0                  #909090
color1                  #d6a7b5
color2                  #adddce
color3                  #f3ddb3
color4                  #8ac0de
color5                  #927acc
color6                  #d9effc
color7                  #e6dce5

color8                  #909090
color9                  #d6a7b5
color10                 #adddce
color11                 #f3ddb3
color12                 #8ac0de
color13                 #927acc
color14                 #d9effc
color15                 #e6dce5

font_family               Fantasque Sans Mono
bold_font                 auto
italic_font               auto
bold_italic_font          auto

font_size                15

disable_ligatures         never

window_padding_width      5

scrollback_lines          1000

enable_audio_bell         no
