#!/bin/sh

bspc config focus_follows_pointer true

# border colors
bspc config focused_border_color \#cba6f7
bspc config normal_border_color \#1e1e2e

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

# bspc config border_width         2
bspc config border_width         0
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on

# Set caps lock to escape
setxkbmap -option caps:escape

# tap to click
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2

# start pulse
pulseaudio &

# Theming stuff
picom & # window opacity
feh --bg-fill --no-xinerama ~/.config/bspwm/walls/the_valley.png & # set background
# polybar &  # open bar on laptop monitor
# MONITOR=HDMI-1 polybar & # open bar on main monitor
