#!/bin/sh


# border colors
bspc config focused_border_color \#cba6f7
bspc config normal_border_color \#1e1e2e

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set caps lock to escape
setxkbmap -option caps:escape

# startup apps
pkill pulseaudio & pulseaudio &
google-chrome-stable &
alacritty &

# Theming stuff
picom & # window opacity
feh --bg-fill --no-xinerama ~/.config/bspwm/walls/the_valley.png & # set background
polybar &  # open bar on laptop monitor
MONITOR=HDMI-A-0 polybar & # open bar on main monitor
